// Code generated by generator.go DO NOT EDIT.
package countries

// All countries
var (
	AF = Country{ISO2: "AF", ISO3: "AFG"}
	AX = Country{ISO2: "AX", ISO3: "ALA"}
	AL = Country{ISO2: "AL", ISO3: "ALB"}
	DZ = Country{ISO2: "DZ", ISO3: "DZA"}
	AS = Country{ISO2: "AS", ISO3: "ASM"}
	AD = Country{ISO2: "AD", ISO3: "AND"}
	AO = Country{ISO2: "AO", ISO3: "AGO"}
	AI = Country{ISO2: "AI", ISO3: "AIA"}
	AQ = Country{ISO2: "AQ", ISO3: "ATA"}
	AG = Country{ISO2: "AG", ISO3: "ATG"}
	AR = Country{ISO2: "AR", ISO3: "ARG"}
	AM = Country{ISO2: "AM", ISO3: "ARM"}
	AW = Country{ISO2: "AW", ISO3: "ABW"}
	AU = Country{ISO2: "AU", ISO3: "AUS"}
	AT = Country{ISO2: "AT", ISO3: "AUT"}
	AZ = Country{ISO2: "AZ", ISO3: "AZE"}
	BS = Country{ISO2: "BS", ISO3: "BHS"}
	BH = Country{ISO2: "BH", ISO3: "BHR"}
	BD = Country{ISO2: "BD", ISO3: "BGD"}
	BB = Country{ISO2: "BB", ISO3: "BRB"}
	BY = Country{ISO2: "BY", ISO3: "BLR"}
	BE = Country{ISO2: "BE", ISO3: "BEL"}
	BZ = Country{ISO2: "BZ", ISO3: "BLZ"}
	BJ = Country{ISO2: "BJ", ISO3: "BEN"}
	BM = Country{ISO2: "BM", ISO3: "BMU"}
	BT = Country{ISO2: "BT", ISO3: "BTN"}
	BO = Country{ISO2: "BO", ISO3: "BOL"}
	BQ = Country{ISO2: "BQ", ISO3: "BES"}
	BA = Country{ISO2: "BA", ISO3: "BIH"}
	BW = Country{ISO2: "BW", ISO3: "BWA"}
	BV = Country{ISO2: "BV", ISO3: "BVT"}
	BR = Country{ISO2: "BR", ISO3: "BRA"}
	IO = Country{ISO2: "IO", ISO3: "IOT"}
	BN = Country{ISO2: "BN", ISO3: "BRN"}
	BG = Country{ISO2: "BG", ISO3: "BGR"}
	BF = Country{ISO2: "BF", ISO3: "BFA"}
	BI = Country{ISO2: "BI", ISO3: "BDI"}
	KH = Country{ISO2: "KH", ISO3: "KHM"}
	CM = Country{ISO2: "CM", ISO3: "CMR"}
	CA = Country{ISO2: "CA", ISO3: "CAN"}
	CV = Country{ISO2: "CV", ISO3: "CPV"}
	KY = Country{ISO2: "KY", ISO3: "CYM"}
	CF = Country{ISO2: "CF", ISO3: "CAF"}
	TD = Country{ISO2: "TD", ISO3: "TCD"}
	CL = Country{ISO2: "CL", ISO3: "CHL"}
	CN = Country{ISO2: "CN", ISO3: "CHN"}
	CX = Country{ISO2: "CX", ISO3: "CXR"}
	CC = Country{ISO2: "CC", ISO3: "CCK"}
	CO = Country{ISO2: "CO", ISO3: "COL"}
	KM = Country{ISO2: "KM", ISO3: "COM"}
	CG = Country{ISO2: "CG", ISO3: "COG"}
	CD = Country{ISO2: "CD", ISO3: "COD"}
	CK = Country{ISO2: "CK", ISO3: "COK"}
	CR = Country{ISO2: "CR", ISO3: "CRI"}
	CI = Country{ISO2: "CI", ISO3: "CIV"}
	HR = Country{ISO2: "HR", ISO3: "HRV"}
	CU = Country{ISO2: "CU", ISO3: "CUB"}
	CW = Country{ISO2: "CW", ISO3: "CUW"}
	CY = Country{ISO2: "CY", ISO3: "CYP"}
	CZ = Country{ISO2: "CZ", ISO3: "CZE"}
	DK = Country{ISO2: "DK", ISO3: "DNK"}
	DJ = Country{ISO2: "DJ", ISO3: "DJI"}
	DM = Country{ISO2: "DM", ISO3: "DMA"}
	DO = Country{ISO2: "DO", ISO3: "DOM"}
	EC = Country{ISO2: "EC", ISO3: "ECU"}
	EG = Country{ISO2: "EG", ISO3: "EGY"}
	SV = Country{ISO2: "SV", ISO3: "SLV"}
	GQ = Country{ISO2: "GQ", ISO3: "GNQ"}
	ER = Country{ISO2: "ER", ISO3: "ERI"}
	EE = Country{ISO2: "EE", ISO3: "EST"}
	ET = Country{ISO2: "ET", ISO3: "ETH"}
	FK = Country{ISO2: "FK", ISO3: "FLK"}
	FO = Country{ISO2: "FO", ISO3: "534"}
	FJ = Country{ISO2: "FJ", ISO3: "FJI"}
	FI = Country{ISO2: "FI", ISO3: "FIN"}
	FR = Country{ISO2: "FR", ISO3: "FRA"}
	GF = Country{ISO2: "GF", ISO3: "GUF"}
	PF = Country{ISO2: "PF", ISO3: "PYF"}
	TF = Country{ISO2: "TF", ISO3: "ATF"}
	GA = Country{ISO2: "GA", ISO3: "GAB"}
	GM = Country{ISO2: "GM", ISO3: "GMB"}
	GE = Country{ISO2: "GE", ISO3: "GEO"}
	DE = Country{ISO2: "DE", ISO3: "DEU"}
	GH = Country{ISO2: "GH", ISO3: "GHA"}
	GI = Country{ISO2: "GI", ISO3: "GIB"}
	GR = Country{ISO2: "GR", ISO3: "GRC"}
	GL = Country{ISO2: "GL", ISO3: "GRL"}
	GD = Country{ISO2: "GD", ISO3: "GRD"}
	GP = Country{ISO2: "GP", ISO3: "GLP"}
	GU = Country{ISO2: "GU", ISO3: "GUM"}
	GT = Country{ISO2: "GT", ISO3: "GTM"}
	GG = Country{ISO2: "GG", ISO3: "GGY"}
	GN = Country{ISO2: "GN", ISO3: "GIN"}
	GW = Country{ISO2: "GW", ISO3: "GNB"}
	GY = Country{ISO2: "GY", ISO3: "GUY"}
	HT = Country{ISO2: "HT", ISO3: "HTI"}
	HM = Country{ISO2: "HM", ISO3: "HMD"}
	VA = Country{ISO2: "VA", ISO3: "VAT"}
	HN = Country{ISO2: "HN", ISO3: "HND"}
	HK = Country{ISO2: "HK", ISO3: "HKG"}
	HU = Country{ISO2: "HU", ISO3: "HUN"}
	IS = Country{ISO2: "IS", ISO3: "ISL"}
	IN = Country{ISO2: "IN", ISO3: "IND"}
	ID = Country{ISO2: "ID", ISO3: "IDN"}
	IR = Country{ISO2: "IR", ISO3: "IRN"}
	IQ = Country{ISO2: "IQ", ISO3: "IRQ"}
	IE = Country{ISO2: "IE", ISO3: "IRL"}
	IM = Country{ISO2: "IM", ISO3: "IMN"}
	IL = Country{ISO2: "IL", ISO3: "ISR"}
	IT = Country{ISO2: "IT", ISO3: "ITA"}
	JM = Country{ISO2: "JM", ISO3: "JAM"}
	JP = Country{ISO2: "JP", ISO3: "JPN"}
	JE = Country{ISO2: "JE", ISO3: "JEY"}
	JO = Country{ISO2: "JO", ISO3: "JOR"}
	KZ = Country{ISO2: "KZ", ISO3: "KAZ"}
	KE = Country{ISO2: "KE", ISO3: "KEN"}
	KI = Country{ISO2: "KI", ISO3: "KIR"}
	KP = Country{ISO2: "KP", ISO3: "PRK"}
	KR = Country{ISO2: "KR", ISO3: "KOR"}
	KW = Country{ISO2: "KW", ISO3: "KWT"}
	KG = Country{ISO2: "KG", ISO3: "KGZ"}
	LA = Country{ISO2: "LA", ISO3: "LAO"}
	LV = Country{ISO2: "LV", ISO3: "LVA"}
	LB = Country{ISO2: "LB", ISO3: "LBN"}
	LS = Country{ISO2: "LS", ISO3: "LSO"}
	LR = Country{ISO2: "LR", ISO3: "LBR"}
	LY = Country{ISO2: "LY", ISO3: "LBY"}
	LI = Country{ISO2: "LI", ISO3: "LIE"}
	LT = Country{ISO2: "LT", ISO3: "LTU"}
	LU = Country{ISO2: "LU", ISO3: "LUX"}
	MO = Country{ISO2: "MO", ISO3: "MAC"}
	MK = Country{ISO2: "MK", ISO3: "MKD"}
	MG = Country{ISO2: "MG", ISO3: "MDG"}
	MW = Country{ISO2: "MW", ISO3: "MWI"}
	MY = Country{ISO2: "MY", ISO3: "MYS"}
	MV = Country{ISO2: "MV", ISO3: "MDV"}
	ML = Country{ISO2: "ML", ISO3: "MLI"}
	MT = Country{ISO2: "MT", ISO3: "MLT"}
	MH = Country{ISO2: "MH", ISO3: "MHL"}
	MQ = Country{ISO2: "MQ", ISO3: "MTQ"}
	MR = Country{ISO2: "MR", ISO3: "MRT"}
	MU = Country{ISO2: "MU", ISO3: "MUS"}
	YT = Country{ISO2: "YT", ISO3: "MYT"}
	MX = Country{ISO2: "MX", ISO3: "MEX"}
	FM = Country{ISO2: "FM", ISO3: "FSM"}
	MD = Country{ISO2: "MD", ISO3: "MDA"}
	MC = Country{ISO2: "MC", ISO3: "MCO"}
	MN = Country{ISO2: "MN", ISO3: "MNG"}
	ME = Country{ISO2: "ME", ISO3: "MNE"}
	MS = Country{ISO2: "MS", ISO3: "MSR"}
	MA = Country{ISO2: "MA", ISO3: "MAR"}
	MZ = Country{ISO2: "MZ", ISO3: "MOZ"}
	MM = Country{ISO2: "MM", ISO3: "MMR"}
	NA = Country{ISO2: "NA", ISO3: "NAM"}
	NR = Country{ISO2: "NR", ISO3: "NRU"}
	NP = Country{ISO2: "NP", ISO3: "NPL"}
	NL = Country{ISO2: "NL", ISO3: "NLD"}
	NC = Country{ISO2: "NC", ISO3: "NCL"}
	NZ = Country{ISO2: "NZ", ISO3: "NZL"}
	NI = Country{ISO2: "NI", ISO3: "NIC"}
	NE = Country{ISO2: "NE", ISO3: "NER"}
	NG = Country{ISO2: "NG", ISO3: "NGA"}
	NU = Country{ISO2: "NU", ISO3: "NIU"}
	NF = Country{ISO2: "NF", ISO3: "NFK"}
	MP = Country{ISO2: "MP", ISO3: "MNP"}
	NO = Country{ISO2: "NO", ISO3: "NOR"}
	PS = Country{ISO2: "PS", ISO3: "PSE"}
	OM = Country{ISO2: "OM", ISO3: "OMN"}
	PK = Country{ISO2: "PK", ISO3: "PAK"}
	PW = Country{ISO2: "PW", ISO3: "PLW"}
	PA = Country{ISO2: "PA", ISO3: "PAN"}
	PG = Country{ISO2: "PG", ISO3: "PNG"}
	PY = Country{ISO2: "PY", ISO3: "PRY"}
	PE = Country{ISO2: "PE", ISO3: "PER"}
	PH = Country{ISO2: "PH", ISO3: "PHL"}
	PN = Country{ISO2: "PN", ISO3: "PCN"}
	PL = Country{ISO2: "PL", ISO3: "POL"}
	PT = Country{ISO2: "PT", ISO3: "PRT"}
	PR = Country{ISO2: "PR", ISO3: "PRI"}
	QA = Country{ISO2: "QA", ISO3: "QAT"}
	RE = Country{ISO2: "RE", ISO3: "REU"}
	RO = Country{ISO2: "RO", ISO3: "ROU"}
	RU = Country{ISO2: "RU", ISO3: "RUS"}
	RW = Country{ISO2: "RW", ISO3: "RWA"}
	BL = Country{ISO2: "BL", ISO3: "534"}
	SH = Country{ISO2: "SH", ISO3: "SHN"}
	KN = Country{ISO2: "KN", ISO3: "KNA"}
	LC = Country{ISO2: "LC", ISO3: "LCA"}
	MF = Country{ISO2: "MF", ISO3: "MAF"}
	PM = Country{ISO2: "PM", ISO3: "SPM"}
	VC = Country{ISO2: "VC", ISO3: "VCT"}
	WS = Country{ISO2: "WS", ISO3: "WSM"}
	SM = Country{ISO2: "SM", ISO3: "SMR"}
	ST = Country{ISO2: "ST", ISO3: "STP"}
	SA = Country{ISO2: "SA", ISO3: "SAU"}
	SN = Country{ISO2: "SN", ISO3: "SEN"}
	RS = Country{ISO2: "RS", ISO3: "SRB"}
	SC = Country{ISO2: "SC", ISO3: "SYC"}
	SL = Country{ISO2: "SL", ISO3: "SLE"}
	SG = Country{ISO2: "SG", ISO3: "SGP"}
	SX = Country{ISO2: "SX", ISO3: "SXM"}
	SK = Country{ISO2: "SK", ISO3: "SVK"}
	SI = Country{ISO2: "SI", ISO3: "SVN"}
	SB = Country{ISO2: "SB", ISO3: "SLB"}
	SO = Country{ISO2: "SO", ISO3: "SOM"}
	ZA = Country{ISO2: "ZA", ISO3: "ZAF"}
	GS = Country{ISO2: "GS", ISO3: "SGS"}
	ES = Country{ISO2: "ES", ISO3: "ESP"}
	LK = Country{ISO2: "LK", ISO3: "LKA"}
	SD = Country{ISO2: "SD", ISO3: "SDN"}
	SR = Country{ISO2: "SR", ISO3: "SUR"}
	SJ = Country{ISO2: "SJ", ISO3: "534"}
	SZ = Country{ISO2: "SZ", ISO3: "SWZ"}
	SE = Country{ISO2: "SE", ISO3: "SWE"}
	CH = Country{ISO2: "CH", ISO3: "CHE"}
	SY = Country{ISO2: "SY", ISO3: "SYR"}
	TW = Country{ISO2: "TW", ISO3: "TWN"}
	TJ = Country{ISO2: "TJ", ISO3: "TJK"}
	TZ = Country{ISO2: "TZ", ISO3: "TZA"}
	TH = Country{ISO2: "TH", ISO3: "THA"}
	TL = Country{ISO2: "TL", ISO3: "TLS"}
	TG = Country{ISO2: "TG", ISO3: "TGO"}
	TK = Country{ISO2: "TK", ISO3: "TKL"}
	TO = Country{ISO2: "TO", ISO3: "TON"}
	TT = Country{ISO2: "TT", ISO3: "TTO"}
	TN = Country{ISO2: "TN", ISO3: "TUN"}
	TR = Country{ISO2: "TR", ISO3: "TUR"}
	TM = Country{ISO2: "TM", ISO3: "TKM"}
	TC = Country{ISO2: "TC", ISO3: "TCA"}
	TV = Country{ISO2: "TV", ISO3: "TUV"}
	UG = Country{ISO2: "UG", ISO3: "UGA"}
	UA = Country{ISO2: "UA", ISO3: "UKR"}
	AE = Country{ISO2: "AE", ISO3: "ARE"}
	GB = Country{ISO2: "GB", ISO3: "GBR"}
	US = Country{ISO2: "US", ISO3: "USA"}
	UM = Country{ISO2: "UM", ISO3: "UMI"}
	UY = Country{ISO2: "UY", ISO3: "URY"}
	UZ = Country{ISO2: "UZ", ISO3: "UZB"}
	VU = Country{ISO2: "VU", ISO3: "VUT"}
	VE = Country{ISO2: "VE", ISO3: "VEN"}
	VN = Country{ISO2: "VN", ISO3: "VNM"}
	VG = Country{ISO2: "VG", ISO3: "VGB"}
	VI = Country{ISO2: "VI", ISO3: "VIR"}
	WF = Country{ISO2: "WF", ISO3: "WLF"}
	EH = Country{ISO2: "EH", ISO3: "ESH"}
	YE = Country{ISO2: "YE", ISO3: "YEM"}
	ZM = Country{ISO2: "ZM", ISO3: "ZMB"}
	ZW = Country{ISO2: "ZW", ISO3: "ZWE"}
)

// Countries defines all countries with they ISO 3166-1 Alpha-2 code as key.
var Countries = map[string]Country{
	"AF": AF,
	"AX": AX,
	"AL": AL,
	"DZ": DZ,
	"AS": AS,
	"AD": AD,
	"AO": AO,
	"AI": AI,
	"AQ": AQ,
	"AG": AG,
	"AR": AR,
	"AM": AM,
	"AW": AW,
	"AU": AU,
	"AT": AT,
	"AZ": AZ,
	"BS": BS,
	"BH": BH,
	"BD": BD,
	"BB": BB,
	"BY": BY,
	"BE": BE,
	"BZ": BZ,
	"BJ": BJ,
	"BM": BM,
	"BT": BT,
	"BO": BO,
	"BQ": BQ,
	"BA": BA,
	"BW": BW,
	"BV": BV,
	"BR": BR,
	"IO": IO,
	"BN": BN,
	"BG": BG,
	"BF": BF,
	"BI": BI,
	"KH": KH,
	"CM": CM,
	"CA": CA,
	"CV": CV,
	"KY": KY,
	"CF": CF,
	"TD": TD,
	"CL": CL,
	"CN": CN,
	"CX": CX,
	"CC": CC,
	"CO": CO,
	"KM": KM,
	"CG": CG,
	"CD": CD,
	"CK": CK,
	"CR": CR,
	"CI": CI,
	"HR": HR,
	"CU": CU,
	"CW": CW,
	"CY": CY,
	"CZ": CZ,
	"DK": DK,
	"DJ": DJ,
	"DM": DM,
	"DO": DO,
	"EC": EC,
	"EG": EG,
	"SV": SV,
	"GQ": GQ,
	"ER": ER,
	"EE": EE,
	"ET": ET,
	"FK": FK,
	"FO": FO,
	"FJ": FJ,
	"FI": FI,
	"FR": FR,
	"GF": GF,
	"PF": PF,
	"TF": TF,
	"GA": GA,
	"GM": GM,
	"GE": GE,
	"DE": DE,
	"GH": GH,
	"GI": GI,
	"GR": GR,
	"GL": GL,
	"GD": GD,
	"GP": GP,
	"GU": GU,
	"GT": GT,
	"GG": GG,
	"GN": GN,
	"GW": GW,
	"GY": GY,
	"HT": HT,
	"HM": HM,
	"VA": VA,
	"HN": HN,
	"HK": HK,
	"HU": HU,
	"IS": IS,
	"IN": IN,
	"ID": ID,
	"IR": IR,
	"IQ": IQ,
	"IE": IE,
	"IM": IM,
	"IL": IL,
	"IT": IT,
	"JM": JM,
	"JP": JP,
	"JE": JE,
	"JO": JO,
	"KZ": KZ,
	"KE": KE,
	"KI": KI,
	"KP": KP,
	"KR": KR,
	"KW": KW,
	"KG": KG,
	"LA": LA,
	"LV": LV,
	"LB": LB,
	"LS": LS,
	"LR": LR,
	"LY": LY,
	"LI": LI,
	"LT": LT,
	"LU": LU,
	"MO": MO,
	"MK": MK,
	"MG": MG,
	"MW": MW,
	"MY": MY,
	"MV": MV,
	"ML": ML,
	"MT": MT,
	"MH": MH,
	"MQ": MQ,
	"MR": MR,
	"MU": MU,
	"YT": YT,
	"MX": MX,
	"FM": FM,
	"MD": MD,
	"MC": MC,
	"MN": MN,
	"ME": ME,
	"MS": MS,
	"MA": MA,
	"MZ": MZ,
	"MM": MM,
	"NA": NA,
	"NR": NR,
	"NP": NP,
	"NL": NL,
	"NC": NC,
	"NZ": NZ,
	"NI": NI,
	"NE": NE,
	"NG": NG,
	"NU": NU,
	"NF": NF,
	"MP": MP,
	"NO": NO,
	"PS": PS,
	"OM": OM,
	"PK": PK,
	"PW": PW,
	"PA": PA,
	"PG": PG,
	"PY": PY,
	"PE": PE,
	"PH": PH,
	"PN": PN,
	"PL": PL,
	"PT": PT,
	"PR": PR,
	"QA": QA,
	"RE": RE,
	"RO": RO,
	"RU": RU,
	"RW": RW,
	"BL": BL,
	"SH": SH,
	"KN": KN,
	"LC": LC,
	"MF": MF,
	"PM": PM,
	"VC": VC,
	"WS": WS,
	"SM": SM,
	"ST": ST,
	"SA": SA,
	"SN": SN,
	"RS": RS,
	"SC": SC,
	"SL": SL,
	"SG": SG,
	"SX": SX,
	"SK": SK,
	"SI": SI,
	"SB": SB,
	"SO": SO,
	"ZA": ZA,
	"GS": GS,
	"ES": ES,
	"LK": LK,
	"SD": SD,
	"SR": SR,
	"SJ": SJ,
	"SZ": SZ,
	"SE": SE,
	"CH": CH,
	"SY": SY,
	"TW": TW,
	"TJ": TJ,
	"TZ": TZ,
	"TH": TH,
	"TL": TL,
	"TG": TG,
	"TK": TK,
	"TO": TO,
	"TT": TT,
	"TN": TN,
	"TR": TR,
	"TM": TM,
	"TC": TC,
	"TV": TV,
	"UG": UG,
	"UA": UA,
	"AE": AE,
	"GB": GB,
	"US": US,
	"UM": UM,
	"UY": UY,
	"UZ": UZ,
	"VU": VU,
	"VE": VE,
	"VN": VN,
	"VG": VG,
	"VI": VI,
	"WF": WF,
	"EH": EH,
	"YE": YE,
	"ZM": ZM,
	"ZW": ZW,
}
